language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
script:
  - npm test
  - npm run lint
  - npm run coverage
  - npm run coverage:coveralls
after_script:
  - cat ./build/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js